version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.6
    networks:
        - app_network
    ports:
      - '3406:3306'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - .docker/database:/bitnami/mariadb

  app:
    image: docker.io/bitnami/laravel:10
    networks:
      - app_network
    ports:
      - '8100-8110:8100-8110'
    environment:
      - LARAVEL_PORT_NUMBER=8100
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_DATABASE=bht_122983_local
      - DB_USERNAME=root
    volumes:
      - './app:/app'
    depends_on:
      - mariadb

networks:
  app_network:
    driver: bridge